[package]
name = "eve_mapper"
version = "0.1.0"
authors = ["Nick Massey <nickmass@nickmass.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.0"
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.110", features = ["derive"] }
tokio = { version = "0.2.20", features = ["full"] }
serde_json = "1.0.53"
glium = "0.27.0"
notify = "4.0.15"
rusttype = {version = "0.9.1", features = ["gpu_cache"] }
hyper = "0.13.6"
webbrowser = "0.5.4"
sha2 = "0.9.1"
base64 = "0.12.3"
rand = "0.7.3"
log = "0.4.8"
uuid = { version = "0.8.1", features = ["v4"] }
env_logger = "0.7.1"
futures = "0.3.5"
flexbuffers = "0.1.1"
httpdate = "0.3.2"
png = "0.16.6"
serde_bytes = "0.11.5"

